import { NextRequest, NextResponse } from 'next/server';
import { GoogleGenerativeAI } from '@google/generative-ai';
import { prisma } from '@/lib/db';

const genAI = process.env.GEMINI_API_KEY ? new GoogleGenerativeAI(process.env.GEMINI_API_KEY) : null;

export async function POST(req: NextRequest) {
  try {
    const { input } = await req.json();

    if (!input || typeof input !== 'string') {
      return NextResponse.json({ error: 'Input text is required' }, { status: 400 });
    }

    const departments = await prisma.department.findMany({ select: { id: true, name: true } });
    const deptList = departments.map(d => `${d.id}: ${d.name}`).join(', ');

    if (!genAI) {
      // Rule-based fallback
      const lower = input.toLowerCase();
      let category = 'Electronics';
      let qty = 1;
      const qtyMatch = input.match(/\b(\d+)\b/);
      if (qtyMatch) qty = parseInt(qtyMatch[1]);

      if (lower.includes('chair') || lower.includes('table') || lower.includes('desk') || lower.includes('sofa') || lower.includes('podium') || lower.includes('board')) {
        category = 'Furniture';
      } else if (lower.includes('room') || lower.includes('hall') || lower.includes('lab') || lower.includes('auditorium') || lower.includes('studio')) {
        category = 'Space';
      } else if (lower.includes('printer') || lower.includes('cutter') || lower.includes('lathe') || lower.includes('cnc') || lower.includes('mill')) {
        category = 'Capacity';
      } else if (lower.includes('chemical') || lower.includes('cable') || lower.includes('filament') || lower.includes('wire')) {
        category = 'Material';
      }

      return NextResponse.json({
        autoFill: {
          name: input.replace(/^\d+\s*/, '').trim() || 'Institutional Resource',
          category,
          quantity: qty,
          condition: 'Good',
          location: 'Main Building, Floor 1',
          estimatedValue: category === 'Electronics' ? 35000 : category === 'Furniture' ? 4500 : 15000,
          departmentId: departments[0]?.id || 'dept-ce',
          description: `${input} available for inter-departmental allocation and campus utility.`,
          tags: `${category.toLowerCase()}, campus, equipment`,
          specifications: { autoGenerated: 'true' },
        },
      });
    }

    const model = genAI.getGenerativeModel({ model: 'gemini-2.0-flash' });
    const prompt = `You are RESCUE AI's intelligent resource cataloging agent.
Given this rough notes or short input from a faculty/staff member: "${input}"
Extract and infer complete catalog specifications for listing this asset.

Available Departments in Organization:
${deptList}

Categories available: "Electronics", "Furniture", "Space", "Capacity", "Material"

Return ONLY valid JSON with this exact schema:
{
  "name": "Proper capitalized product name",
  "category": "Electronics" | "Furniture" | "Space" | "Capacity" | "Material",
  "quantity": number,
  "condition": "Excellent" | "Good" | "Fair",
  "location": "e.g. Block A, Room 204",
  "estimatedValue": number (in Indian Rupees INR, e.g. 45000),
  "departmentId": "matched department id from list above, or closest fit",
  "description": "Professional 2-sentence description of the asset and potential use cases",
  "tags": "comma,separated,search,tags",
  "specifications": { "key1": "value1", "key2": "value2" }
}`;

    const result = await model.generateContent(prompt);
    const text = result.response.text().replace(/```json\n?|```/g, '').trim();
    const autoFill = JSON.parse(text);

    return NextResponse.json({ autoFill });
  } catch (e: any) {
    console.error('AutoFill AI error:', e);
    return NextResponse.json({
      autoFill: {
        name: 'New Asset',
        category: 'Electronics',
        quantity: 1,
        condition: 'Good',
        location: 'Campus Store',
        estimatedValue: 15000,
        description: 'Asset catalog entry ready for review.',
        tags: 'equipment, asset',
      },
    });
  }
}
